[build]
builder = "NIXPACKS"
buildCommand = "cargo build --release"

[deploy]
startCommand = "target/release/rust-llm-service"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
RUST_LOG = "info"
HOST = "0.0.0.0"
PORT = "$PORT"

[networking]
publicPort = 80